// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi_YvOi-lMcsBtN78-BGoCT_2BiO2EiSM',
    appId: '1:635109082618:web:35059e0726ed3ae7109043',
    messagingSenderId: '635109082618',
    projectId: 'ecommerce-2f35d',
    authDomain: 'ecommerce-2f35d.firebaseapp.com',
    storageBucket: 'ecommerce-2f35d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBltvqE52Dha_jHX1_UNpGn79dTfHq6YEs',
    appId: '1:635109082618:android:2e50568fbe6fb2b4109043',
    messagingSenderId: '635109082618',
    projectId: 'ecommerce-2f35d',
    storageBucket: 'ecommerce-2f35d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjgenI-4ttJnaOSilsQSYzcwmQ_9q6pf4',
    appId: '1:635109082618:ios:61998eee05fd6439109043',
    messagingSenderId: '635109082618',
    projectId: 'ecommerce-2f35d',
    storageBucket: 'ecommerce-2f35d.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}